import { DataTable } from "@/registry/bases/takumi/components/data-table/data-table";
import { Heading } from "@/registry/bases/takumi/components/heading/heading";
import { KeyValue } from "@/registry/bases/takumi/components/key-value/key-value";
import { Section } from "@/registry/bases/takumi/components/section/section";
import { PdfcnThemeProvider } from "@/registry/bases/takumi/components/theme-provider";
import { Document, Page } from "@/registry/bases/takumi/lib/pdf-primitives";

const data = [
  {
    date: "01 Sep 2026",
    refNo: "RCP-C0U-0001",
    type: "Credit",
    description: "Opening Balance",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 50000,
  },
  {
    date: "01 Sep 2026",
    refNo: "INV-001",
    type: "Debit",
    description: "Office Supplies",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 48500,
  },
  {
    date: "02 Sep 2026",
    refNo: "INV-002",
    type: "Credit",
    description: "Client Payment - Acme Corp",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 58500,
  },
  {
    date: "02 Sep 2026",
    refNo: "INV-003",
    type: "Debit",
    description: "Software License",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 56500,
  },
  {
    date: "03 Sep 2026",
    refNo: "INV-004",
    type: "Debit",
    description: "Travel Expense",
    status: "Un-Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 56500,
  },
  {
    date: "03 Sep 2026",
    refNo: "INV-005",
    type: "Credit",
    description: "Service Revenue",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 61500,
  },
  {
    date: "04 Sep 2026",
    refNo: "INV-006",
    type: "Debit",
    description: "Internet Bill",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 60200,
  },
  {
    date: "04 Sep 2026",
    refNo: "INV-007",
    type: "Debit",
    description: "Electricity Bill",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 58700,
  },
  {
    date: "05 Sep 2026",
    refNo: "INV-008",
    type: "Credit",
    description: "Consulting Fee",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 63700,
  },
  {
    date: "05 Sep 2026",
    refNo: "INV-009",
    type: "Debit",
    description: "Printer Toner",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 62700,
  },
  {
    date: "06 Sep 2026",
    refNo: "INV-010",
    type: "Credit",
    description: "Client Payment - Beta Ltd",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 72700,
  },
  {
    date: "06 Sep 2026",
    refNo: "INV-011",
    type: "Debit",
    description: "Courier Service",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 71500,
  },
  {
    date: "07 Sep 2026",
    refNo: "INV-012",
    type: "Debit",
    description: "Team Lunch",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 69500,
  },
  {
    date: "07 Sep 2026",
    refNo: "INV-013",
    type: "Credit",
    description: "Product Sale",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 74500,
  },
  {
    date: "08 Sep 2026",
    refNo: "INV-014",
    type: "Debit",
    description: "Stationery",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 73900,
  },
  {
    date: "08 Sep 2026",
    refNo: "INV-015",
    type: "Debit",
    description: "Parking Fees",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 73600,
  },
  {
    date: "09 Sep 2026",
    refNo: "INV-016",
    type: "Credit",
    description: "Freelance Work",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 78600,
  },
  {
    date: "09 Sep 2026",
    refNo: "INV-017",
    type: "Debit",
    description: "Server Hosting",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 76600,
  },
  {
    date: "10 Sep 2026",
    refNo: "INV-018",
    type: "Credit",
    description: "Client Payment - Gamma Inc",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 86600,
  },
  {
    date: "10 Sep 2026",
    refNo: "INV-019",
    type: "Debit",
    description: "Office Rent",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 76600,
  },
  {
    date: "11 Sep 2026",
    refNo: "INV-020",
    type: "Debit",
    description: "Maintenance",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 75600,
  },
  {
    date: "11 Sep 2026",
    refNo: "INV-021",
    type: "Credit",
    description: "Commission Income",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 80600,
  },
  {
    date: "12 Sep 2026",
    refNo: "INV-022",
    type: "Debit",
    description: "Advertising",
    status: "Un-Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 80600,
  },
  {
    date: "12 Sep 2026",
    refNo: "INV-023",
    type: "Credit",
    description: "Product Sale",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 85600,
  },
  {
    date: "13 Sep 2026",
    refNo: "INV-024",
    type: "Debit",
    description: "Insurance Premium",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 83600,
  },
  {
    date: "13 Sep 2026",
    refNo: "INV-025",
    type: "Credit",
    description: "Client Payment - Delta Co",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 93600,
  },
  {
    date: "14 Sep 2026",
    refNo: "INV-026",
    type: "Debit",
    description: "Petrol",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 92800,
  },
  {
    date: "14 Sep 2026",
    refNo: "INV-027",
    type: "Debit",
    description: "Phone Bill",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 92100,
  },
  {
    date: "15 Sep 2026",
    refNo: "INV-028",
    type: "Credit",
    description: "Retainer Fee",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 97100,
  },
  {
    date: "15 Sep 2026",
    refNo: "INV-029",
    type: "Debit",
    description: "Cleaning Service",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 96300,
  },
  {
    date: "16 Sep 2026",
    refNo: "INV-030",
    type: "Credit",
    description: "Client Payment - Epsilon",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 106300,
  },
  {
    date: "16 Sep 2026",
    refNo: "INV-031",
    type: "Debit",
    description: "Software Update",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 104300,
  },
  {
    date: "17 Sep 2026",
    refNo: "INV-032",
    type: "Debit",
    description: "Staff Training",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 101300,
  },
  {
    date: "17 Sep 2026",
    refNo: "INV-033",
    type: "Credit",
    description: "Product Sale",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 106300,
  },
  {
    date: "18 Sep 2026",
    refNo: "INV-034",
    type: "Debit",
    description: "Legal Fees",
    status: "Un-Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 106300,
  },
  {
    date: "18 Sep 2026",
    refNo: "INV-035",
    type: "Credit",
    description: "Consulting Revenue",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 111300,
  },
  {
    date: "19 Sep 2026",
    refNo: "INV-036",
    type: "Debit",
    description: "Mailbox Rental",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 110800,
  },
  {
    date: "19 Sep 2026",
    refNo: "INV-037",
    type: "Credit",
    description: "Client Payment - Zeta Ltd",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 120800,
  },
  {
    date: "20 Sep 2026",
    refNo: "INV-038",
    type: "Debit",
    description: "Gym Membership",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 119800,
  },
  {
    date: "20 Sep 2026",
    refNo: "INV-039",
    type: "Debit",
    description: "Security System",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 118300,
  },
  {
    date: "21 Sep 2026",
    refNo: "INV-040",
    type: "Credit",
    description: "Royalty Income",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 123300,
  },
  {
    date: "21 Sep 2026",
    refNo: "INV-041",
    type: "Debit",
    description: "Subscriptions",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 122000,
  },
  {
    date: "22 Sep 2026",
    refNo: "INV-042",
    type: "Credit",
    description: "Client Payment - Eta Corp",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 132000,
  },
  {
    date: "22 Sep 2026",
    refNo: "INV-043",
    type: "Debit",
    description: "Conference Fee",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 130000,
  },
  {
    date: "23 Sep 2026",
    refNo: "INV-044",
    type: "Debit",
    description: "Transport",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 129200,
  },
  {
    date: "23 Sep 2026",
    refNo: "INV-045",
    type: "Credit",
    description: "Service Revenue",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 134200,
  },
  {
    date: "24 Sep 2026",
    refNo: "INV-046",
    type: "Debit",
    description: "Catering",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 133000,
  },
  {
    date: "24 Sep 2026",
    refNo: "INV-047",
    type: "Credit",
    description: "Client Payment - Theta Inc",
    status: "Paid",
    chargedBy: "Bilal Noor",
    balanceAfter: 143000,
  },
  {
    date: "25 Sep 2026",
    refNo: "INV-048",
    type: "Debit",
    description: "Miscellaneous",
    status: "Paid",
    chargedBy: "System",
    balanceAfter: 142500,
  },
  {
    date: "25 Sep 2026",
    refNo: "INV-049",
    type: "Credit",
    description: "Bonus Income",
    status: "Paid",
    chargedBy: "Sara Ahmed",
    balanceAfter: 147500,
  },
  {
    date: "26 Sep 2026",
    refNo: "INV-050",
    type: "Debit",
    description: "Year-End Adjustment",
    status: "Paid",
    chargedBy: "Ali Khan",
    balanceAfter: 146000,
  },
].map((data) => {
  return {
    _detail: (
      <KeyValue
        items={[
          { key: "Invoice", value: data.date },
          { key: "Party Name", value: data.chargedBy },
        ]}
      />
    ),
    ...data,
  };
});

const DemoBody = () => (
  <Section spacing="none">
    <Heading level={3}>Ledger</Heading>
    <DataTable
      size="compact"
      variant="grid"
      columns={[
        { header: "Date", key: "date" },
        { header: "Ref No", key: "refNo" },
        { header: "Type", key: "type" },
        { header: "Description", key: "description" },
        { align: "center", header: "Status", key: "status" },
        { header: "Charged By", key: "chargedBy" },
        { align: "right", header: "Balance After", key: "balanceAfter" },
      ]}
      data={data}
    />
  </Section>
);

const Demo = () => (
  <Document>
    <Page size="A4">
      <PdfcnThemeProvider>
        <DemoBody />
      </PdfcnThemeProvider>
    </Page>
  </Document>
);

export default Demo;
